### ISSUE TITLE
Shouldn't it also check STUN magic cookie?

### ISSUE THREAD

**Issue by ibc** [nodertc/is-stun#1]
I mean [this](https://github.com/versatica/mediasoup/blob/v3/worker/include/RTC/StunMessage.hpp#L118).

**Comment by reklatsmasters** [comment]
Magic cookie is part of [rfc5389](https://tools.ietf.org/html/rfc5389#section-6). So, i want to leave ability to detect RFC3489 messages.

> The magic cookie field MUST contain the fixed value 0x2112A442 in
  network byte order.  In RFC 3489 [RFC3489], this field was part of
  the transaction ID; placing the magic cookie in this location allows
  a server to detect if the client will understand certain attributes
  that were added in this revised specification.

**Comment by ibc** [comment]
Fair. I understood this library was focused on RFC 5389.
